// بيانات تجريبية خيالية بالكامل. لا منتجات حقيقية ولا أسعار حقيقية ولا إحصائيات حقيقية.
// Fictional demo data only. Edited copies live in each visitor's own browser (localStorage).
window.ALETHEA_SEED = {
  version: 1,
  categories: [
    { id: "tools",    icon: "tool",    name: { ar: "أدوات رقمية",   en: "Digital Tools" } },
    { id: "apps",     icon: "app",     name: { ar: "تطبيقات",       en: "Applications" } },
    { id: "design",   icon: "layers",  name: { ar: "حزم تصميم",     en: "Design Packs" } },
    { id: "creative", icon: "spark",   name: { ar: "موارد إبداعية", en: "Creative Resources" } },
    { id: "services", icon: "compass", name: { ar: "خدمات",         en: "Services" } }
  ],
  products: [
    { id: "p-nebula-ui", status: "published", featured: true, cat: "design", price: 29, oldPrice: 39, avail: "available",
      name: { ar: "حزمة واجهات نيبيولا", en: "Nebula UI Kit" },
      desc: { ar: "مجموعة واجهات زجاجية جاهزة بأكثر من 120 مكوّناً تجريبياً: أزرار، بطاقات، قوائم، ونماذج بتدرجات لونية متناسقة. منتج تجريبي للعرض فقط.",
              en: "A glassy interface kit with 120+ demo components: buttons, cards, menus and forms in blended gradients. Demo product, display only." },
      tags: ["ui", "glass", "figma"], badge: { ar: "خصم 25%", en: "-25%" }, art: { style: "mesh", hue: 235 }, image: "", gallery: [] },
    { id: "p-aurora-grad", status: "published", featured: true, cat: "design", price: 12, oldPrice: 0, avail: "available",
      name: { ar: "حزمة تدرجات أورورا", en: "Aurora Gradient Pack" },
      desc: { ar: "٦٠ خلفية تدرجية بألوان الشفق: أزرق وأخضر وبنفسجي بدرجات هادئة. مثالية للعروض والمنشورات. (عينة تجريبية)",
              en: "60 aurora-toned gradient backdrops blending blue, green and violet. Great for slides and posts. (Demo sample)" },
      tags: ["gradients", "backgrounds"], badge: { ar: "جديد", en: "New" }, art: { style: "waves", hue: 165 }, image: "", gallery: [] },
    { id: "p-promptdeck", status: "published", featured: true, cat: "apps", price: 19, oldPrice: 0, avail: "available",
      name: { ar: "برومبت ديك", en: "PromptDeck" },
      desc: { ar: "تطبيق تجريبي لتنظيم الأفكار والقوالب النصية في بطاقات قابلة للسحب. هذا وصف خيالي لمنتج غير موجود.",
              en: "A demo app for organizing ideas and text templates in draggable cards. A fictional description of a product that does not exist." },
      tags: ["app", "productivity"], badge: { ar: "الأكثر طلباً", en: "Popular" }, art: { style: "prism", hue: 265 }, image: "", gallery: [] },
    { id: "p-pixelforge", status: "published", featured: false, cat: "tools", price: 24, oldPrice: 0, avail: "limited",
      name: { ar: "حقيبة بيكسل فورج", en: "Pixel Forge Toolkit" },
      desc: { ar: "أدوات تجريبية لتجهيز الصور وتغيير أحجامها وتصديرها بدفعات. الكمية المعروضة محدودة لأغراض العرض فقط.",
              en: "Demo tools for preparing, resizing and batch-exporting images. Limited availability shown for display purposes only." },
      tags: ["images", "batch"], badge: { ar: "كمية محدودة", en: "Limited" }, art: { style: "grid", hue: 200 }, image: "", gallery: [] },
    { id: "p-motion", status: "published", featured: true, cat: "creative", price: 15, oldPrice: 20, avail: "available",
      name: { ar: "إعدادات حركة ١", en: "Motion Presets Vol. 1" },
      desc: { ar: "٣٠ إعداداً مسبقاً لحركات انسيابية للعناوين والانتقالات. بيانات تجريبية.",
              en: "30 smooth motion presets for titles and transitions. Demo data." },
      tags: ["motion", "video"], badge: { ar: "عرض", en: "Deal" }, art: { style: "orbit", hue: 150 }, image: "", gallery: [] },
    { id: "p-soundbloom", status: "published", featured: false, cat: "creative", price: 18, oldPrice: 0, avail: "soon",
      name: { ar: "عينات ساوند بلوم", en: "Sound Bloom Samples" },
      desc: { ar: "مكتبة أصوات هادئة وأجواء مستقبلية. قادمة قريباً (للعرض فقط، لا توجد ملفات).",
              en: "A library of calm, futuristic ambience. Coming soon (display only, no files exist)." },
      tags: ["audio", "ambient"], badge: { ar: "قريباً", en: "Soon" }, art: { style: "waves", hue: 280 }, image: "", gallery: [] },
    { id: "p-orbit-planner", status: "published", featured: false, cat: "apps", price: 0, oldPrice: 0, avail: "available",
      name: { ar: "مخطط أوربت", en: "Orbit Planner" },
      desc: { ar: "تطبيق تخطيط مهام تجريبي مجاني بتصميم مداري. لا يوجد تطبيق فعلي، العرض لتجربة بطاقة مجانية.",
              en: "A free demo task-planner concept with an orbital design. No real app exists; this card tests a free item." },
      tags: ["app", "planner", "free"], badge: { ar: "مجاني", en: "Free" }, art: { style: "orbit", hue: 190 }, image: "", gallery: [] },
    { id: "p-brand-starter", status: "published", featured: true, cat: "services", price: 149, oldPrice: 0, avail: "available",
      name: { ar: "باقة هوية البداية", en: "Brand Starter Service" },
      desc: { ar: "خدمة تجريبية لتصميم هوية بصرية أولية: شعار، ألوان، وخطوط. لا يتم تنفيذ أي طلب فعلي في هذا العرض.",
              en: "A demo service for an initial visual identity: logo, colors and type. No real order is fulfilled in this preview." },
      tags: ["service", "branding"], badge: { ar: "خدمة", en: "Service" }, art: { style: "prism", hue: 245 }, image: "", gallery: [] },
    { id: "p-landing-sprint", status: "published", featured: false, cat: "services", price: 249, oldPrice: 299, avail: "limited",
      name: { ar: "سبرنت صفحة هبوط", en: "Landing Page Sprint" },
      desc: { ar: "خدمة تجريبية لبناء صفحة هبوط في أسبوع. السعر والمدة للعرض فقط.",
              en: "A demo service for building a landing page in a week. Price and duration are for display only." },
      tags: ["service", "web"], badge: { ar: "فرصة محدودة", en: "Limited slot" }, art: { style: "mesh", hue: 180 }, image: "", gallery: [] },
    { id: "p-glass-icons", status: "published", featured: false, cat: "design", price: 9, oldPrice: 0, avail: "available",
      name: { ar: "أيقونات زجاجية", en: "Glass Icons Set" },
      desc: { ar: "٢٠٠ أيقونة تجريبية بحواف مضيئة وإضاءة ناعمة.", en: "200 demo icons with luminous edges and soft lighting." },
      tags: ["icons", "glass"], badge: { ar: "", en: "" }, art: { style: "grid", hue: 215 }, image: "", gallery: [] },
    { id: "p-theme-studio", status: "published", featured: false, cat: "tools", price: 22, oldPrice: 0, avail: "available",
      name: { ar: "ستوديو الثيمات", en: "Theme Studio" },
      desc: { ar: "أداة تجريبية لتوليد لوحات ألوان متناسقة وتصديرها. (وصف خيالي)", en: "A demo tool for generating and exporting harmonious color palettes. (Fictional description)" },
      tags: ["colors", "theme"], badge: { ar: "جديد", en: "New" }, art: { style: "mesh", hue: 290 }, image: "", gallery: [] },
    { id: "p-bot-starter", status: "published", featured: false, cat: "tools", price: 14, oldPrice: 0, avail: "available",
      name: { ar: "بداية بوت المجتمع", en: "Community Bot Starter" },
      desc: { ar: "قالب تجريبي لبوت مجتمعي بسيط. لا يتصل بأي منصة في هذا العرض.", en: "A demo template for a simple community bot. It connects to no platform in this preview." },
      tags: ["bot", "community"], badge: { ar: "", en: "" }, art: { style: "prism", hue: 170 }, image: "", gallery: [] }
  ],
  projects: [
    { id: "pr-1", status: "published", hue: 230, link: "", tags: ["web", "3d"],
      title: { ar: "كون الشفق", en: "Aurora Cosmos" }, desc: { ar: "تجربة ويب تفاعلية بخلفيات شفقية وجزيئات خفيفة. مشروع تجريبي للعرض.", en: "An interactive web experience with aurora backdrops and light particles. A demo showcase project." } },
    { id: "pr-2", status: "published", hue: 160, link: "", tags: ["brand"],
      title: { ar: "هوية موجة", en: "Wave Identity" }, desc: { ar: "نظام هوية بصرية خيالي لعلامة تقنية ناشئة.", en: "A fictional visual identity system for an emerging tech brand." } },
    { id: "pr-3", status: "published", hue: 275, link: "", tags: ["app", "ui"],
      title: { ar: "واجهة مدار", en: "Orbit Interface" }, desc: { ar: "تصميم واجهة تطبيق بطاقات عائمة وانتقالات ناعمة.", en: "An app interface design with floating cards and soft transitions." } },
    { id: "pr-4", status: "published", hue: 195, link: "", tags: ["motion"],
      title: { ar: "عنوان متحرك", en: "Kinetic Titles" }, desc: { ar: "سلسلة عناوين متحركة بتدرجات ضوئية.", en: "A series of animated titles with light gradients." } },
    { id: "pr-5", status: "published", hue: 250, link: "", tags: ["tools"],
      title: { ar: "مختبر الألوان", en: "Color Lab" }, desc: { ar: "أداة تجريبية لمزج الألوان ومعاينة التدرجات مباشرة.", en: "A demo tool to blend colors and preview gradients live." } },
    { id: "pr-6", status: "published", hue: 140, link: "", tags: ["community"],
      title: { ar: "ساحة المجتمع", en: "Community Plaza" }, desc: { ar: "فكرة لمساحة مجتمعية متعددة القنوات، خيالية للعرض.", en: "A concept for a multi-channel community space, fictional for display." } }
  ],
  tools: [
    { id: "t-1", icon: "palette", hue: 235, status: { ar: "نموذج أولي", en: "Prototype" }, name: { ar: "مختبر الألوان", en: "Color Lab" }, desc: { ar: "امزج الألوان وجرّب التدرجات.", en: "Blend colors and try gradients." } },
    { id: "t-2", icon: "image", hue: 175, status: { ar: "فكرة", en: "Concept" }, name: { ar: "ضاغط الصور", en: "Image Squeezer" }, desc: { ar: "تصغير الصور قبل النشر.", en: "Shrink images before publishing." } },
    { id: "t-3", icon: "type", hue: 265, status: { ar: "نموذج أولي", en: "Prototype" }, name: { ar: "مولّد الخطوط", en: "Type Pairing" }, desc: { ar: "اقتراح أزواج خطوط متناسقة.", en: "Suggest harmonious font pairs." } },
    { id: "t-4", icon: "grid", hue: 205, status: { ar: "قيد التخطيط", en: "Planned" }, name: { ar: "منظّم المشاريع", en: "Project Board" }, desc: { ar: "لوحة بطاقات لتتبع الأعمال.", en: "A card board to track work." } },
    { id: "t-5", icon: "wave", hue: 150, status: { ar: "فكرة", en: "Concept" }, name: { ar: "مصمم الموجات", en: "Wave Designer" }, desc: { ar: "ارسم موجات SVG وصدّرها.", en: "Draw SVG waves and export them." } },
    { id: "t-6", icon: "bolt", hue: 285, status: { ar: "قيد التخطيط", en: "Planned" }, name: { ar: "مسرّع الأفكار", en: "Idea Booster" }, desc: { ar: "قوالب لبدء المشاريع بسرعة.", en: "Templates to start projects fast." } }
  ],
  services: [
    { id: "s-1", icon: "layers", hue: 240, name: { ar: "تصميم الهوية", en: "Brand Identity" }, desc: { ar: "شعار وألوان وخطوط ودليل استخدام.", en: "Logo, colors, type and usage guide." } },
    { id: "s-2", icon: "app", hue: 170, name: { ar: "تصميم واجهات", en: "Interface Design" }, desc: { ar: "شاشات تطبيقات ومواقع بتجربة سلسة.", en: "App and web screens with a smooth experience." } },
    { id: "s-3", icon: "code", hue: 270, name: { ar: "تطوير مواقع", en: "Web Development" }, desc: { ar: "مواقع سريعة ومتجاوبة مع الهاتف.", en: "Fast, mobile-friendly websites." } },
    { id: "s-4", icon: "film", hue: 195, name: { ar: "حركة ومحتوى", en: "Motion & Content" }, desc: { ar: "عناوين متحركة ومحتوى مرئي للمنصات.", en: "Animated titles and visual content for platforms." } }
  ],
  announcements: [
    { id: "a-1", status: "published", pinned: true, date: "2026-10-01",
      title: { ar: "انطلاق النسخة التجريبية", en: "Experimental preview is live" },
      body: { ar: "هذه نسخة عرض تجريبية. كل المنتجات والأسعار خيالية ولا توجد عمليات شراء حقيقية.", en: "This is an experimental preview. All products and prices are fictional and no real purchases happen." } },
    { id: "a-2", status: "published", pinned: false, date: "2026-09-24",
      title: { ar: "لوحة ألوان جديدة", en: "New color studio" },
      body: { ar: "جرّب تغيير الثيم من زر الألوان في أعلى الصفحة: أوشن، أورورا، إميرالد، فيوليت.", en: "Try the color button at the top: Ocean, Aurora, Emerald, Violet." } },
    { id: "a-3", status: "published", pinned: false, date: "2026-09-12",
      title: { ar: "المتجر التجريبي", en: "Demo store opened" },
      body: { ar: "تصفّح البطاقات وأضف إلى السلة وجرّب الدفع المحاكى بدون أي رسوم.", en: "Browse cards, add to cart and try the simulated checkout with no charges." } },
    { id: "a-4", status: "published", pinned: false, date: "2026-09-02",
      title: { ar: "خطط قادمة", en: "What's next" },
      body: { ar: "ربط قاعدة بيانات حقيقية وحسابات للمدراء يأتي في مرحلة لاحقة، بعد الاختبار.", en: "A real database and admin accounts come in a later stage, after testing." } }
  ],
  // أقسام الصفحة الرئيسية: true = ظاهر
  sections: { stats: true, explore: true, featured: true, projects: true, tools: true, services: true, news: true, community: true },
  // روابط تجريبية. اتركها فارغة حتى تضع روابطك الحقيقية من لوحة التحكم > الروابط.
  socials: { youtube: "", instagram: "", discord: "", website: "", email: "" }
};
